---
services:
- db-calc-sandbox
- calc-env
- calc-redis
applications:
- name: calc-sandbox
  instances: 1
  memory: 256M
  disk_quota: 1024M
  host: calc-sandbox
  domain: apps.cloud.gov
  buildpack: python_buildpack
  command: bash cf.sh
  stack: cflinuxfs2
  timeout: 180
  env:
    EMAIL_URL: 'console:'
- name: calc-rqworker
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqworker default
  stack: cflinuxfs2
  timeout: 180
  env:
    EMAIL_URL: 'console:'
- name: calc-rqscheduler
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqscheduler
  stack: cflinuxfs2
  timeout: 180
  env:
    EMAIL_URL: "console:"
    IS_RQ_SCHEDULER: "yup"
