---
services:
- db-calc-dev
- calc-env
- calc-redis
applications:
- name: calc-dev
  instances: 1
  memory: 256M
  disk_quota: 1024M
  host: calc-dev
  domain: apps.cloud.gov
  buildpack: python_buildpack
  command: bash cf.sh
  stack: cflinuxfs2
  timeout: 180
  env:
    NEW_RELIC_APP_NAME: "CALC (staging)"
    NEW_RELIC_CONFIG_FILE: "newrelic.ini"
    NEW_RELIC_ENV: "staging"
    NEW_RELIC_LOG: "stdout"
- name: calc-rqworker
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqworker default
  stack: cflinuxfs2
  timeout: 180
- name: calc-rqscheduler
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqscheduler
  stack: cflinuxfs2
  timeout: 180
  env:
    IS_RQ_SCHEDULER: "yup"
